# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main", "test" ]  # Adicionando a branch test
  pull_request:
    branches: [ "main", "test" ]   # Também adicionando para pull requests

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: maven
      - name: Run Tests with Maven
        run: |
          mvn clean install
          mvn clean test
          mvn package

      - name: Generate Site with Maven
        run: mvn site  # Gera o site

      - name: Upload Artefatos
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-testes
          path: ./target/site/

      - name: Upload Package
        uses: actions/upload-artifact@v4
        with:
          name: pacote
          path: ./target/*.jar

  notification:
    needs: test

    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Get Commit Author Email
        id: get_email
        run: echo "COMMIT_AUTHOR_EMAIL=$(git log -1 --pretty=format:'%ae')" >> $GITHUB_ENV

      - name: Install Sendmail
        run: |
          sudo apt-get update
          sudo apt-get install -y sendmail

      - name: Send Email Notification
        run: |
          python scripts/send_email.py
        env:
          COMMIT_AUTHOR_EMAIL: ${{ env.COMMIT_AUTHOR_EMAIL }}
