name: Java CI with Maven

on:
  push:
    branches: [ "main", "test" ]
  pull_request:
    branches: [ "main", "test" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: maven
      - name: Run Tests with Maven
        run: |
          mvn clean install
          mvn clean test
          mvn package

      - name: Generate Site with Maven
        run: mvn site

      - name: Upload Artefatos
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-testes
          path: ./target/site/

      - name: Upload Package
        uses: actions/upload-artifact@v4
        with:
          name: pacote
          path: ./target/*.jar

  notification:
    needs: test

    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Get Commit Author Email
        id: get_email
        run: echo "COMMIT_AUTHOR_EMAIL=$(git log -1 --pretty=format:'%ae')" >> $GITHUB_ENV

      - name: Send Email Notification
        run: |
          python scripts/send_email.py
        env:
          COMMIT_AUTHOR_EMAIL: ${{ env.COMMIT_AUTHOR_EMAIL }}
          FROM_EMAIL: ${{ secrets.FROM_EMAIL }}         # Endereço de e-mail do remetente
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}   # Senha do e-mail
